# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{stylo}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["mwagg"]
  s.date = %q{2010-09-21}
  s.description = %q{Server side stylesheet combining for readonly hosting environments}
  s.email = %q{michael@guerillatactics.co.uk}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/stylo.rb",
     "lib/stylo/config.rb",
     "lib/stylo/processor.rb",
     "lib/stylo/rack.rb",
     "lib/stylo/railtie.rb",
     "spec/processor_spec.rb",
     "spec/rack_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/mwagg/stylo}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Server side stylesheet combining for readonly hosting environments}
  s.test_files = [
    "spec/processor_spec.rb",
     "spec/rack_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end

