# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{stylo}
  s.version = "0.6.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["mwagg"]
  s.date = %q{2010-11-03}
  s.description = %q{Server side stylesheet combining for readonly hosting environments}
  s.email = %q{michael@guerillatactics.co.uk}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc",
     "TODO"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "TODO",
     "cucumber.yml",
     "features/fixtures.rb",
     "features/fixtures/child.css",
     "features/fixtures/child.js",
     "features/fixtures/grand_parent.css",
     "features/fixtures/grand_parent.js",
     "features/fixtures/grand_parent_with_parent_with_child.css",
     "features/fixtures/grand_parent_with_parent_with_child.js",
     "features/fixtures/nested_folder_grand_parent.css",
     "features/fixtures/nested_folder_grand_parent_with_parent_with_child.css",
     "features/fixtures/parent.css",
     "features/fixtures/parent.js",
     "features/fixtures/parent_with_child.css",
     "features/fixtures/parent_with_child.js",
     "features/fixtures/processed_sass_child.css",
     "features/fixtures/processed_sass_which_uses_mixin.css",
     "features/fixtures/sass_child.scss",
     "features/fixtures/sass_mixins.scss",
     "features/fixtures/sass_which_uses_mixin.scss",
     "features/javascripts.feature",
     "features/response_headers.feature",
     "features/sass_integration.feature",
     "features/step_definitions/stylo_steps.rb",
     "features/stylesheets.feature",
     "features/stylo_cannot_serve_asset.feature",
     "features/support/env.rb",
     "lib/stylo.rb",
     "lib/stylo/asset_loader.rb",
     "lib/stylo/combiner.rb",
     "lib/stylo/config.rb",
     "lib/stylo/pipeline_steps/caching.rb",
     "lib/stylo/pipeline_steps/javascript.rb",
     "lib/stylo/pipeline_steps/sass.rb",
     "lib/stylo/pipeline_steps/stylesheet.rb",
     "lib/stylo/processor.rb",
     "lib/stylo/rack.rb",
     "lib/stylo/railtie.rb",
     "lib/stylo/response.rb",
     "spec/asset_loader_spec.rb",
     "spec/combiner_spec.rb",
     "spec/pipeline_steps/caching_spec.rb",
     "spec/pipeline_steps/javascript_spec.rb",
     "spec/pipeline_steps/sass_spec.rb",
     "spec/pipeline_steps/stylesheet_spec.rb",
     "spec/rack_spec.rb",
     "spec/spec_helper.rb",
     "spec/stylo_spec_helpers.rb",
     "stylo.gemspec"
  ]
  s.homepage = %q{http://github.com/mwagg/stylo}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Server side stylesheet combining for readonly hosting environments}
  s.test_files = [
    "spec/asset_loader_spec.rb",
     "spec/combiner_spec.rb",
     "spec/pipeline_steps/caching_spec.rb",
     "spec/pipeline_steps/javascript_spec.rb",
     "spec/pipeline_steps/sass_spec.rb",
     "spec/pipeline_steps/stylesheet_spec.rb",
     "spec/rack_spec.rb",
     "spec/spec_helper.rb",
     "spec/stylo_spec_helpers.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
      s.add_development_dependency(%q<rack-test>, [">= 0"])
      s.add_development_dependency(%q<sinatra>, [">= 0"])
      s.add_development_dependency(%q<rails>, [">= 3.0.0"])
      s.add_runtime_dependency(%q<haml>, [">= 3.0.21"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<cucumber>, [">= 0"])
      s.add_dependency(%q<rack-test>, [">= 0"])
      s.add_dependency(%q<sinatra>, [">= 0"])
      s.add_dependency(%q<rails>, [">= 3.0.0"])
      s.add_dependency(%q<haml>, [">= 3.0.21"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<cucumber>, [">= 0"])
    s.add_dependency(%q<rack-test>, [">= 0"])
    s.add_dependency(%q<sinatra>, [">= 0"])
    s.add_dependency(%q<rails>, [">= 3.0.0"])
    s.add_dependency(%q<haml>, [">= 3.0.21"])
  end
end

